name: Build and Publish Docker Images
# Build image for Backend and for Frontend
on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: davidpik   # statické lowercase jméno, žádné problémy s GHCR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.IMAGE_NAMESPACE }}
          password: ${{ secrets.GITHUB_TOKEN }}

      ###############################################
      # BACKEND IMAGE
      ###############################################
      - name: Build backend image
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/step-ui-backend:latest \
            ./backend

      - name: Push backend image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/step-ui-backend:latest

      ###############################################
      # FRONTEND IMAGE
      ###############################################
      - name: Build frontend image  # build zvlášť
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/step-ui-frontend:latest \
            ./frontend

      - name: Push frontend image   # push zvlášť
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/step-ui-frontend:latest
